include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

image: node:lts-alpine

stages:
  - build
  - test
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

before_script:
  - npm ci --cache .npm --prefer-offline

build-docs:
  stage: build
  script:
    - npm run build:docs
  artifacts:
    paths:
      - web/dist

jest:
  stage: test
  script:
    - npm run postpublish
    - npm run test:ci
  artifacts:
    when: always
    reports:
      junit:
        - test-results/jest/junit.xml

pages:
  stage: deploy
  script:
    - mv web/dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
